"""add management context entries

Revision ID: 130ad5f63fdd
Revises: 20260905_0008
Create Date: 2026-09-06 11:36:16.717052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '130ad5f63fdd'
down_revision: Union[str, Sequence[str], None] = '20260905_0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_context_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_management_context_entries'))
    )
    op.create_index(op.f('ix_management_context_entries_category'), 'management_context_entries', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_management_context_entries_category'), table_name='management_context_entries')
    op.drop_table('management_context_entries')
    # ### end Alembic commands ###
