"""complete manager agent v1

Revision ID: 4789b4339244
Revises: 20260907_0009
Create Date: 2026-09-09 00:25:52.624065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4789b4339244'
down_revision: Union[str, Sequence[str], None] = '20260907_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # PostgreSQL enum values are append-only. SQLAlchemy autogenerate detects
    # the column types but not the new values, so add them explicitly before
    # application code can write the new V1 lifecycle/events.
    op.execute("ALTER TYPE escalation_status ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL'")
    op.execute("ALTER TYPE escalation_status ADD VALUE IF NOT EXISTS 'APPROVED'")
    op.execute("ALTER TYPE escalation_status ADD VALUE IF NOT EXISTS 'REJECTED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'DAILY_UPDATE_CREATED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'DAILY_UPDATE_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'BLOCKER_DEPENDENCY_OWNER_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'BLOCKER_STATUS_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'ESCALATION_APPROVED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'ESCALATION_REJECTED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'ESCALATION_ACKNOWLEDGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'TASK_OWNER_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'TASK_DEADLINE_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'PROJECT_OWNER_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'PROJECT_TARGET_DATE_CHANGED'")
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'EMPLOYEE_MANAGER_CHANGED'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='escalation_decision_type'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authorized_action', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['employees.id'], name=op.f('fk_escalation_decisions_decided_by_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalations.id'], name=op.f('fk_escalation_decisions_escalation_id_escalations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_decisions')),
    sa.UniqueConstraint('escalation_id', name='uq_escalation_decisions_escalation')
    )
    op.create_index(op.f('ix_escalation_decisions_decided_at'), 'escalation_decisions', ['decided_at'], unique=False)
    op.create_index(op.f('ix_escalation_decisions_decided_by'), 'escalation_decisions', ['decided_by'], unique=False)
    op.create_index(op.f('ix_escalation_decisions_decision'), 'escalation_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_escalation_decisions_escalation_id'), 'escalation_decisions', ['escalation_id'], unique=False)
    op.add_column('agent_runs', sa.Column('expected_outcome', sa.Text(), nullable=True))
    op.add_column('daily_updates', sa.Column('expected_outcome', sa.Text(), nullable=True))
    op.add_column('escalations', sa.Column('requested_target_date', sa.Date(), nullable=True))
    op.add_column('escalations', sa.Column('requested_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('management_context_entries', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_management_context_entries_is_active'), 'management_context_entries', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_management_context_entries_is_active'), table_name='management_context_entries')
    op.drop_column('management_context_entries', 'is_active')
    op.drop_column('escalations', 'requested_deadline')
    op.drop_column('escalations', 'requested_target_date')
    op.drop_column('daily_updates', 'expected_outcome')
    op.drop_column('agent_runs', 'expected_outcome')
    op.drop_index(op.f('ix_escalation_decisions_escalation_id'), table_name='escalation_decisions')
    op.drop_index(op.f('ix_escalation_decisions_decision'), table_name='escalation_decisions')
    op.drop_index(op.f('ix_escalation_decisions_decided_by'), table_name='escalation_decisions')
    op.drop_index(op.f('ix_escalation_decisions_decided_at'), table_name='escalation_decisions')
    op.drop_table('escalation_decisions')
    # PostgreSQL does not safely remove enum values. Leaving append-only
    # operational-event values is preferable to a destructive type rebuild.
