"""add organisational memory foundation

Revision ID: 4a7274691244
Revises: 130ad5f63fdd
Create Date: 2026-09-06 12:52:10.278464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a7274691244'
down_revision: Union[str, Sequence[str], None] = '130ad5f63fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('subject_text', sa.Text(), nullable=True),
    sa.Column('predicate', sa.Enum('OWNS', 'RESPONSIBLE_FOR', 'WORKING_ON', 'DEPENDS_ON', 'BLOCKED_BY', 'REQUIRES', 'MANAGED_BY', 'PART_OF_PROJECT', 'COLLABORATES_WITH', 'WAITING_ON', 'APPROVED_BY', 'RESOLVED_BY', 'DECIDED_BY', 'AFFECTS', name='memory_predicate'), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('object_text', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('CURRENT', 'SUPERSEDED', 'DISPUTED', 'EXPIRED', name='memory_fact_status'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('supersedes_fact_id', sa.UUID(), nullable=True),
    sa.Column('visibility_scope', sa.Enum('PRIVATE_1TO1', 'MANAGER_ONLY', 'PROJECT', 'TEAM', 'ORGANISATION', name='visibility_scope'), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_fact_id'], ['memory_facts.id'], name=op.f('fk_memory_facts_supersedes_fact_id_memory_facts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_facts'))
    )
    op.create_index(op.f('ix_memory_facts_importance'), 'memory_facts', ['importance'], unique=False)
    op.create_index(op.f('ix_memory_facts_object_id'), 'memory_facts', ['object_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_object_type'), 'memory_facts', ['object_type'], unique=False)
    op.create_index(op.f('ix_memory_facts_observed_at'), 'memory_facts', ['observed_at'], unique=False)
    op.create_index(op.f('ix_memory_facts_predicate'), 'memory_facts', ['predicate'], unique=False)
    op.create_index(op.f('ix_memory_facts_status'), 'memory_facts', ['status'], unique=False)
    op.create_index(op.f('ix_memory_facts_subject_id'), 'memory_facts', ['subject_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_subject_type'), 'memory_facts', ['subject_type'], unique=False)
    op.create_index(op.f('ix_memory_facts_supersedes_fact_id'), 'memory_facts', ['supersedes_fact_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_valid_from'), 'memory_facts', ['valid_from'], unique=False)
    op.create_index(op.f('ix_memory_facts_valid_until'), 'memory_facts', ['valid_until'], unique=False)
    op.create_index(op.f('ix_memory_facts_visibility_scope'), 'memory_facts', ['visibility_scope'], unique=False)
    op.create_table('memory_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='memory_job_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_jobs')),
    sa.UniqueConstraint('job_type', 'source_id', name='uq_memory_jobs_type_source')
    )
    op.create_index(op.f('ix_memory_jobs_job_type'), 'memory_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_memory_jobs_scheduled_at'), 'memory_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_memory_jobs_source_id'), 'memory_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_memory_jobs_status'), 'memory_jobs', ['status'], unique=False)
    op.create_table('memory_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=64), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Enum('OWNS', 'RESPONSIBLE_FOR', 'WORKING_ON', 'DEPENDS_ON', 'BLOCKED_BY', 'REQUIRES', 'MANAGED_BY', 'PART_OF_PROJECT', 'COLLABORATES_WITH', 'WAITING_ON', 'APPROVED_BY', 'RESOLVED_BY', 'DECIDED_BY', 'AFFECTS', name='memory_predicate'), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('CURRENT', 'SUPERSEDED', 'DISPUTED', 'EXPIRED', name='memory_fact_status'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('visibility_scope', sa.Enum('PRIVATE_1TO1', 'MANAGER_ONLY', 'PROJECT', 'TEAM', 'ORGANISATION', name='visibility_scope'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_relations'))
    )
    op.create_index(op.f('ix_memory_relations_importance'), 'memory_relations', ['importance'], unique=False)
    op.create_index(op.f('ix_memory_relations_relation_type'), 'memory_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_memory_relations_source_entity_id'), 'memory_relations', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_memory_relations_source_entity_type'), 'memory_relations', ['source_entity_type'], unique=False)
    op.create_index(op.f('ix_memory_relations_status'), 'memory_relations', ['status'], unique=False)
    op.create_index(op.f('ix_memory_relations_target_entity_id'), 'memory_relations', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_memory_relations_target_entity_type'), 'memory_relations', ['target_entity_type'], unique=False)
    op.create_index(op.f('ix_memory_relations_valid_from'), 'memory_relations', ['valid_from'], unique=False)
    op.create_index(op.f('ix_memory_relations_valid_until'), 'memory_relations', ['valid_until'], unique=False)
    op.create_index(op.f('ix_memory_relations_visibility_scope'), 'memory_relations', ['visibility_scope'], unique=False)
    op.create_table('memory_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_summaries')),
    sa.UniqueConstraint('scope', 'entity_id', 'period_start', 'period_end', name='uq_memory_summaries_scope_period')
    )
    op.create_index(op.f('ix_memory_summaries_entity_id'), 'memory_summaries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_memory_summaries_period_end'), 'memory_summaries', ['period_end'], unique=False)
    op.create_index(op.f('ix_memory_summaries_period_start'), 'memory_summaries', ['period_start'], unique=False)
    op.create_index(op.f('ix_memory_summaries_scope'), 'memory_summaries', ['scope'], unique=False)
    op.create_table('management_procedures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('CANDIDATE', 'APPROVED', 'REJECTED', 'RETIRED', name='management_procedure_status'), nullable=False),
    sa.Column('supporting_episode_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], name=op.f('fk_management_procedures_approved_by_employees'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_management_procedures')),
    sa.UniqueConstraint('name', name=op.f('uq_management_procedures_name'))
    )
    op.create_index(op.f('ix_management_procedures_status'), 'management_procedures', ['status'], unique=False)
    op.create_table('memory_episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_type', sa.Enum('BLOCKER', 'RESOLUTION', 'DECISION', 'DELIVERY', 'INCIDENT', 'DEADLINE_CHANGE', 'DEPENDENCY', 'PROJECT_EVENT', 'OTHER', name='memory_episode_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('primary_employee_id', sa.UUID(), nullable=True),
    sa.Column('visibility_scope', sa.Enum('PRIVATE_1TO1', 'MANAGER_ONLY', 'PROJECT', 'TEAM', 'ORGANISATION', name='visibility_scope'), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_employee_id'], ['employees.id'], name=op.f('fk_memory_episodes_primary_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_memory_episodes_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_episodes'))
    )
    op.create_index(op.f('ix_memory_episodes_ended_at'), 'memory_episodes', ['ended_at'], unique=False)
    op.create_index(op.f('ix_memory_episodes_episode_type'), 'memory_episodes', ['episode_type'], unique=False)
    op.create_index(op.f('ix_memory_episodes_importance'), 'memory_episodes', ['importance'], unique=False)
    op.create_index(op.f('ix_memory_episodes_primary_employee_id'), 'memory_episodes', ['primary_employee_id'], unique=False)
    op.create_index(op.f('ix_memory_episodes_project_id'), 'memory_episodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_memory_episodes_started_at'), 'memory_episodes', ['started_at'], unique=False)
    op.create_index(op.f('ix_memory_episodes_visibility_scope'), 'memory_episodes', ['visibility_scope'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('MESSAGE_RECEIVED', 'MESSAGE_SENT', 'DAILY_UPDATE_RECEIVED', 'BLOCKER_CREATED', 'BLOCKER_RESOLVED', 'COMMITMENT_CREATED', 'COMMITMENT_COMPLETED', 'COMMITMENT_MISSED', 'COMMITMENT_REVISED', 'ESCALATION_CREATED', 'ESCALATION_RESOLVED', name='activity_event_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('actor_employee_id', sa.UUID(), nullable=True),
    sa.Column('subject_employee_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='memory_job_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['employees.id'], name=op.f('fk_activity_events_actor_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_activity_events_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_employee_id'], ['employees.id'], name=op.f('fk_activity_events_subject_employee_id_employees'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_activity_events_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_events')),
    sa.UniqueConstraint('idempotency_key', name='uq_activity_events_idempotency_key')
    )
    op.create_index(op.f('ix_activity_events_actor_employee_id'), 'activity_events', ['actor_employee_id'], unique=False)
    op.create_index(op.f('ix_activity_events_entity_id'), 'activity_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_events_entity_type'), 'activity_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_events_event_type'), 'activity_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_events_occurred_at'), 'activity_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_activity_events_processing_status'), 'activity_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_activity_events_project_id'), 'activity_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_activity_events_source_id'), 'activity_events', ['source_id'], unique=False)
    op.create_index(op.f('ix_activity_events_source_type'), 'activity_events', ['source_type'], unique=False)
    op.create_index(op.f('ix_activity_events_subject_employee_id'), 'activity_events', ['subject_employee_id'], unique=False)
    op.create_index(op.f('ix_activity_events_task_id'), 'activity_events', ['task_id'], unique=False)
    op.create_table('memory_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('activity_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_event_id'], ['activity_events.id'], name=op.f('fk_memory_sources_activity_event_id_activity_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_memory_sources_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_memory_sources_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_sources')),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_memory_sources_source')
    )
    op.create_index(op.f('ix_memory_sources_activity_event_id'), 'memory_sources', ['activity_event_id'], unique=False)
    op.create_index(op.f('ix_memory_sources_conversation_id'), 'memory_sources', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_sources_message_id'), 'memory_sources', ['message_id'], unique=False)
    op.create_index(op.f('ix_memory_sources_source_id'), 'memory_sources', ['source_id'], unique=False)
    op.create_index(op.f('ix_memory_sources_source_type'), 'memory_sources', ['source_type'], unique=False)
    op.create_table('memory_evidence_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('memory_kind', sa.String(length=32), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('memory_source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_source_id'], ['memory_sources.id'], name=op.f('fk_memory_evidence_links_memory_source_id_memory_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_evidence_links')),
    sa.UniqueConstraint('memory_kind', 'memory_id', 'memory_source_id', name='uq_memory_evidence_link')
    )
    op.create_index(op.f('ix_memory_evidence_links_memory_id'), 'memory_evidence_links', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_evidence_links_memory_kind'), 'memory_evidence_links', ['memory_kind'], unique=False)
    op.create_index(op.f('ix_memory_evidence_links_memory_source_id'), 'memory_evidence_links', ['memory_source_id'], unique=False)
    # Full-text retrieval is available without an embedding deployment.
    op.execute("CREATE INDEX ix_memory_facts_full_text ON memory_facts USING GIN (to_tsvector('simple', coalesce(subject_text, '') || ' ' || coalesce(object_text, '')))")
    op.execute("CREATE INDEX ix_memory_episodes_full_text ON memory_episodes USING GIN (to_tsvector('simple', title || ' ' || summary))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_memory_episodes_full_text")
    op.execute("DROP INDEX IF EXISTS ix_memory_facts_full_text")
    op.drop_index(op.f('ix_memory_evidence_links_memory_source_id'), table_name='memory_evidence_links')
    op.drop_index(op.f('ix_memory_evidence_links_memory_kind'), table_name='memory_evidence_links')
    op.drop_index(op.f('ix_memory_evidence_links_memory_id'), table_name='memory_evidence_links')
    op.drop_table('memory_evidence_links')
    op.drop_index(op.f('ix_memory_sources_source_type'), table_name='memory_sources')
    op.drop_index(op.f('ix_memory_sources_source_id'), table_name='memory_sources')
    op.drop_index(op.f('ix_memory_sources_message_id'), table_name='memory_sources')
    op.drop_index(op.f('ix_memory_sources_conversation_id'), table_name='memory_sources')
    op.drop_index(op.f('ix_memory_sources_activity_event_id'), table_name='memory_sources')
    op.drop_table('memory_sources')
    op.drop_index(op.f('ix_activity_events_task_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_subject_employee_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_source_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_source_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_project_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_processing_status'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_occurred_at'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_event_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_entity_type'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_entity_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_actor_employee_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_memory_episodes_visibility_scope'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_started_at'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_project_id'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_primary_employee_id'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_importance'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_episode_type'), table_name='memory_episodes')
    op.drop_index(op.f('ix_memory_episodes_ended_at'), table_name='memory_episodes')
    op.drop_table('memory_episodes')
    op.drop_index(op.f('ix_management_procedures_status'), table_name='management_procedures')
    op.drop_table('management_procedures')
    op.drop_index(op.f('ix_memory_summaries_scope'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_period_start'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_period_end'), table_name='memory_summaries')
    op.drop_index(op.f('ix_memory_summaries_entity_id'), table_name='memory_summaries')
    op.drop_table('memory_summaries')
    op.drop_index(op.f('ix_memory_relations_visibility_scope'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_valid_until'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_valid_from'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_target_entity_type'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_target_entity_id'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_status'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_source_entity_type'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_source_entity_id'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_relation_type'), table_name='memory_relations')
    op.drop_index(op.f('ix_memory_relations_importance'), table_name='memory_relations')
    op.drop_table('memory_relations')
    op.drop_index(op.f('ix_memory_jobs_status'), table_name='memory_jobs')
    op.drop_index(op.f('ix_memory_jobs_source_id'), table_name='memory_jobs')
    op.drop_index(op.f('ix_memory_jobs_scheduled_at'), table_name='memory_jobs')
    op.drop_index(op.f('ix_memory_jobs_job_type'), table_name='memory_jobs')
    op.drop_table('memory_jobs')
    op.drop_index(op.f('ix_memory_facts_visibility_scope'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_valid_until'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_valid_from'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_supersedes_fact_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_subject_type'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_subject_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_status'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_predicate'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_observed_at'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_object_type'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_object_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_importance'), table_name='memory_facts')
    op.drop_table('memory_facts')
    # ### end Alembic commands ###
