"""add issue scoped response decisions and llm usage

Revision ID: 524786cdfa8a
Revises: 4789b4339244
Create Date: 2026-09-09 13:30:49.800852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '524786cdfa8a'
down_revision: Union[str, Sequence[str], None] = '4789b4339244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE activity_event_type ADD VALUE IF NOT EXISTS 'TASK_STATUS_CHANGED'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('deployment', sa.String(length=255), nullable=False),
    sa.Column('feature', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_input_cost_usd', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('estimated_output_cost_usd', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('estimated_total_cost_usd', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('pricing_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index(op.f('ix_llm_usage_conversation_id'), 'llm_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_feature'), 'llm_usage', ['feature'], unique=False)
    op.create_index(op.f('ix_llm_usage_message_id'), 'llm_usage', ['message_id'], unique=False)
    op.create_index(op.f('ix_llm_usage_model'), 'llm_usage', ['model'], unique=False)
    op.create_index(op.f('ix_llm_usage_timestamp'), 'llm_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
    op.create_table('blocker_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocker_id'], ['blockers.id'], name=op.f('fk_blocker_dependencies_blocker_id_blockers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_blocker_dependencies_employee_id_employees'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocker_dependencies')),
    sa.UniqueConstraint('blocker_id', 'employee_id', name=op.f('uq_blocker_dependencies_blocker_id'))
    )
    op.create_index(op.f('ix_blocker_dependencies_blocker_id'), 'blocker_dependencies', ['blocker_id'], unique=False)
    op.create_index(op.f('ix_blocker_dependencies_employee_id'), 'blocker_dependencies', ['employee_id'], unique=False)
    op.create_table('conversation_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('awaiting_field', sa.String(length=40), nullable=False),
    sa.Column('answered_by_message_id', sa.UUID(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answered_by_message_id'], ['messages.id'], name=op.f('fk_conversation_questions_answered_by_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['blocker_id'], ['blockers.id'], name=op.f('fk_conversation_questions_blocker_id_blockers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_questions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_conversation_questions_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_conversation_questions_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_questions')),
    sa.UniqueConstraint('message_id', name=op.f('uq_conversation_questions_message_id'))
    )
    op.create_index(op.f('ix_conversation_questions_blocker_id'), 'conversation_questions', ['blocker_id'], unique=False)
    op.create_index(op.f('ix_conversation_questions_conversation_id'), 'conversation_questions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_questions_task_id'), 'conversation_questions', ['task_id'], unique=False)
    op.create_table('conversation_states',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('last_user_message_id', sa.UUID(), nullable=True),
    sa.Column('active_blocker_id', sa.UUID(), nullable=True),
    sa.Column('active_task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_blocker_id'], ['blockers.id'], name=op.f('fk_conversation_states_active_blocker_id_blockers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['active_task_id'], ['tasks.id'], name=op.f('fk_conversation_states_active_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_states_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_user_message_id'], ['messages.id'], name=op.f('fk_conversation_states_last_user_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversation_states'))
    )
    op.add_column('agent_runs', sa.Column('decision_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_runs', sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_runs', sa.Column('state_applied', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('messages', sa.Column('reply_to_external_id', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('quoted_content', sa.Text(), nullable=True))
    op.create_index(op.f('ix_messages_reply_to_external_id'), 'messages', ['reply_to_external_id'], unique=False)
    # Preserve existing single-owner links when introducing per-owner progress.
    op.execute("""
        INSERT INTO blocker_dependencies (id, blocker_id, employee_id, is_active, resolved_at)
        SELECT md5(id::text || dependency_owner_id::text)::uuid, id, dependency_owner_id, true, resolved_at
        FROM blockers WHERE dependency_owner_id IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_reply_to_external_id'), table_name='messages')
    op.drop_column('messages', 'quoted_content')
    op.drop_column('messages', 'reply_to_external_id')
    op.drop_column('agent_runs', 'state_applied')
    op.drop_column('agent_runs', 'context_json')
    op.drop_column('agent_runs', 'decision_json')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_conversation_questions_task_id'), table_name='conversation_questions')
    op.drop_index(op.f('ix_conversation_questions_conversation_id'), table_name='conversation_questions')
    op.drop_index(op.f('ix_conversation_questions_blocker_id'), table_name='conversation_questions')
    op.drop_table('conversation_questions')
    op.drop_index(op.f('ix_blocker_dependencies_employee_id'), table_name='blocker_dependencies')
    op.drop_index(op.f('ix_blocker_dependencies_blocker_id'), table_name='blocker_dependencies')
    op.drop_table('blocker_dependencies')
    op.drop_index(op.f('ix_llm_usage_user_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_timestamp'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_model'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_message_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_feature'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_conversation_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
